spring:
  data:
    redis:
      host: localhost
      port: 6379
  
  datasource:
    url: jdbc:postgresql://localhost:5432/triagedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  jackson:
    time-zone: Asia/Kolkata
    serialization:
      write-dates-as-timestamps: false

server:
  error:
    include-stacktrace: never

ai:
  ollama:
    url: http://localhost:11434/api
    model: phi3
    num_ctx: 2048
    num_threads: 4
    num_gpu: 0


rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 5
        auto-startup: true