spring:
  data:
    redis:
      url: ${SPRING_REDIS_URL:redis://redis:6379}
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/triagedb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  jackson:
    time-zone: Asia/Kolkata
    serialization:
      write-dates-as-timestamps: false

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    connection-timeout: 5000
    listener:
      simple:
        concurrency: 3
        max-concurrency: 5
        auto-startup: true
        declaration-retries: 10
        missing-queues-fatal: false
        recovery-backoff: 5000

server:
  error:
    include-stacktrace: never

ai:
  provider: huggingface
  huggingface:
    url: https://router.huggingface.co/v1/chat/completions
    model: ${HF_MODEL}
    token: ${HF_TOKEN}